# Makefile generated by BNFC.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Arabica/Test

# Rules for building the parser.

Arabica/Abs.hs Arabica/Lex.x Arabica/Par.y Arabica/Print.hs Arabica/Test.hs : arabica.cf
	bnfc --haskell -d arabica.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Arabica/Test : Arabica/Abs.hs Arabica/Lex.hs Arabica/Par.hs Arabica/Print.hs Arabica/Test.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f Arabica/*.hi Arabica/*.o Arabica/*.log Arabica/*.aux Arabica/*.dvi

distclean : clean
	-rm -f Arabica/Abs.hs Arabica/Abs.hs.bak Arabica/ComposOp.hs Arabica/ComposOp.hs.bak Arabica/Doc.txt Arabica/Doc.txt.bak Arabica/ErrM.hs Arabica/ErrM.hs.bak Arabica/Layout.hs Arabica/Layout.hs.bak Arabica/Lex.x Arabica/Lex.x.bak Arabica/Par.y Arabica/Par.y.bak Arabica/Print.hs Arabica/Print.hs.bak Arabica/Skel.hs Arabica/Skel.hs.bak Arabica/Test.hs Arabica/Test.hs.bak Arabica/XML.hs Arabica/XML.hs.bak Arabica/AST.agda Arabica/AST.agda.bak Arabica/Parser.agda Arabica/Parser.agda.bak Arabica/IOLib.agda Arabica/IOLib.agda.bak Arabica/Main.agda Arabica/Main.agda.bak Arabica/arabica.dtd Arabica/arabica.dtd.bak Arabica/Test Arabica/Lex.hs Arabica/Par.hs Arabica/Par.info Arabica/ParData.hs Makefile
	-rmdir -p Arabica/

# EOF
