{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintArabica.
--   Generated by the BNF converter.

module PrintArabica where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsArabica

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsArabica.Ident where
  prt _ (AbsArabica.Ident i) = doc $ showString i

instance Print AbsArabica.Program where
  prt i = \case
    AbsArabica.Program topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print AbsArabica.TopDef where
  prt i = \case
    AbsArabica.FnDef type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsArabica.TopDef] where
  prt = prtList

instance Print AbsArabica.Arg where
  prt i = \case
    AbsArabica.Arg type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsArabica.Arg] where
  prt = prtList

instance Print AbsArabica.Block where
  prt i = \case
    AbsArabica.Block stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [AbsArabica.Stmt] where
  prt = prtList

instance Print AbsArabica.Stmt where
  prt i = \case
    AbsArabica.Empty -> prPrec i 0 (concatD [doc (showString ";")])
    AbsArabica.BStmt block -> prPrec i 0 (concatD [prt 0 block])
    AbsArabica.Decl type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    AbsArabica.Ass id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsArabica.Ret expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsArabica.VRet -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsArabica.CondElse expr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])
    AbsArabica.Cond expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsArabica.While expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsArabica.ForTo item expr stmt -> prPrec i 0 (concatD [doc (showString "for"), prt 0 item, doc (showString "to"), prt 0 expr, doc (showString "do"), prt 0 stmt])
    AbsArabica.ForDownTo item expr stmt -> prPrec i 0 (concatD [doc (showString "for"), prt 0 item, doc (showString "downto"), prt 0 expr, doc (showString "do"), prt 0 stmt])
    AbsArabica.SPrint expr -> prPrec i 0 (concatD [doc (showString "print("), prt 0 expr, doc (showString ")")])
    AbsArabica.SExp expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsArabica.Item where
  prt i = \case
    AbsArabica.NoInit id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsArabica.Init id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsArabica.Item] where
  prt = prtList

instance Print AbsArabica.Type where
  prt i = \case
    AbsArabica.Int -> prPrec i 0 (concatD [doc (showString "int")])
    AbsArabica.Str -> prPrec i 0 (concatD [doc (showString "string")])
    AbsArabica.Bool -> prPrec i 0 (concatD [doc (showString "boolean")])
    AbsArabica.Void -> prPrec i 0 (concatD [doc (showString "void")])
    AbsArabica.Fun type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsArabica.Type] where
  prt = prtList

instance Print AbsArabica.Expr where
  prt i = \case
    AbsArabica.EVar id_ -> prPrec i 6 (concatD [prt 0 id_])
    AbsArabica.ELitInt n -> prPrec i 6 (concatD [prt 0 n])
    AbsArabica.ELitTrue -> prPrec i 6 (concatD [doc (showString "true")])
    AbsArabica.ELitFalse -> prPrec i 6 (concatD [doc (showString "false")])
    AbsArabica.EApp id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsArabica.EString str -> prPrec i 6 (concatD [prt 0 str])
    AbsArabica.EtoString expr -> prPrec i 5 (concatD [doc (showString "toString("), prt 6 expr, doc (showString ")")])
    AbsArabica.EtoInt expr -> prPrec i 5 (concatD [doc (showString "toInt("), prt 6 expr, doc (showString ")")])
    AbsArabica.Neg expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsArabica.Not expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AbsArabica.EMul expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsArabica.EAdd expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsArabica.ERel expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsArabica.EAnd expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AbsArabica.EOr expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsArabica.Expr] where
  prt = prtList

instance Print AbsArabica.AddOp where
  prt i = \case
    AbsArabica.Plus -> prPrec i 0 (concatD [doc (showString "+")])
    AbsArabica.Minus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print AbsArabica.MulOp where
  prt i = \case
    AbsArabica.Times -> prPrec i 0 (concatD [doc (showString "*")])
    AbsArabica.Div -> prPrec i 0 (concatD [doc (showString "/")])

instance Print AbsArabica.RelOp where
  prt i = \case
    AbsArabica.LTH -> prPrec i 0 (concatD [doc (showString "<")])
    AbsArabica.LE -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsArabica.GTH -> prPrec i 0 (concatD [doc (showString ">")])
    AbsArabica.GE -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsArabica.EQU -> prPrec i 0 (concatD [doc (showString "==")])
    AbsArabica.NE -> prPrec i 0 (concatD [doc (showString "!=")])

